import { addDynamicIconSelectors } from "@iconify/tailwind";
import daisyui from "daisyui";
import typography from "@tailwindcss/typography";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "media",
  content: ["./src/**/*.{html,js,svelte,ts}"],
  theme: {
    extend: {
      colors: {
        "base-content-100": "var(--base-content-100)",
        "base-content-200": "var(--base-content-200)",
        "base-content-300": "var(--base-content-300)",
        "level-1": "var(--level-1)",
        "level-2": "var(--level-2)",
        "level-3": "var(--level-3)",
      },
    },
  },
  plugins: [daisyui, typography, addDynamicIconSelectors()],
  daisyui: {
    themes: [
      {
        black: {
          "base-content": "#ffffff",
          "base-100": "#000000",
          "base-200": "#0d0d0d",
          "base-300": "#1a1a1a",
          primary: "#60a5fa",
          "primary-focus": "#3b82f6",
          "primary-content": "#ffffff",
          secondary: "#525252",
          "secondary-focus": "#666666",
          "secondary-content": "#ffffff",
          accent: "#404040",
          "accent-focus": "#4a4a4a",
          "accent-content": "#ffffff",
          neutral: "#262626",
          "neutral-focus": "#303030",
          "neutral-content": "#ffffff",
          info: "#38bdf8",
          "info-focus": "#0ea5e9",
          "info-content": "#ffffff",
          success: "#4ade80",
          "success-focus": "#22c55e",
          "success-content": "#ffffff",
          warning: "#fbbf24",
          "warning-focus": "#f59e0b",
          "warning-content": "#000000",
          error: "#f87171",
          "error-focus": "#ef4444",
          "error-content": "#ffffff",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.75rem",
          "--rounded-badge": "1.9rem",
          "--animation-btn": ".25s",
          "--animation-input": ".2s",
          "--btn-text-case": "lowercase",
          "--navbar-padding": ".5rem",
          "--border-btn": "1px",
        },
        light: {
          "base-content": "#1f2937",
          "base-100": "#ffffff",
          "base-200": "#f8fafc",
          "base-300": "#f1f5f9",
          primary: "#3b82f6",
          "primary-focus": "#2563eb",
          "primary-content": "#ffffff",
          secondary: "#64748b",
          "secondary-focus": "#475569",
          "secondary-content": "#ffffff",
          accent: "#818cf8",
          "accent-focus": "#6366f1",
          "accent-content": "#ffffff",
          neutral: "#e2e8f0",
          "neutral-focus": "#cbd5e1",
          "neutral-content": "#1f2937",
          info: "#0ea5e9",
          "info-focus": "#0284c7",
          "info-content": "#ffffff",
          success: "#22c55e",
          "success-focus": "#16a34a",
          "success-content": "#ffffff",
          warning: "#f59e0b",
          "warning-focus": "#d97706",
          "warning-content": "#000000",
          error: "#ef4444",
          "error-focus": "#dc2626",
          "error-content": "#ffffff",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.75rem",
          "--rounded-badge": "1.9rem",
          "--animation-btn": ".25s",
          "--animation-input": ".2s",
          "--btn-text-case": "lowercase",
          "--navbar-padding": ".5rem",
          "--border-btn": "1px",
        },
        dark: {
          "base-content": "#f2f2f2",
          "base-100": "#111827",
          "base-200": "#1f2937",
          "base-300": "#374151",
          primary: "#60a5fa",
          "primary-focus": "#3b82f6",
          "primary-content": "#ffffff",
          secondary: "#6b7280",
          "secondary-focus": "#4b5563",
          "secondary-content": "#ffffff",
          accent: "#818cf8",
          "accent-focus": "#6366f1",
          "accent-content": "#ffffff",
          neutral: "#374151",
          "neutral-focus": "#4b5563",
          "neutral-content": "#ffffff",
          info: "#38bdf8",
          "info-focus": "#0ea5e9",
          "info-content": "#ffffff",
          success: "#4ade80",
          "success-focus": "#22c55e",
          "success-content": "#ffffff",
          warning: "#fbbf24",
          "warning-focus": "#f59e0b",
          "warning-content": "#000000",
          error: "#f87171",
          "error-focus": "#ef4444",
          "error-content": "#ffffff",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.75rem",
          "--rounded-badge": "1.9rem",
          "--animation-btn": ".25s",
          "--animation-input": ".2s",
          "--btn-text-case": "lowercase",
          "--navbar-padding": ".5rem",
          "--border-btn": "1px",
        },
      },
    ],
  },
};
